SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE TABLE IF NOT EXISTS `taw`.`USUARIO` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(80) NOT NULL,
  `EMAIL` VARCHAR(45) NOT NULL,
  `SENHA` VARCHAR(45) NOT NULL,
  `ESTADO` VARCHAR(45) BINARY NULL DEFAULT NULL,
  `CIDADE` VARCHAR(45) BINARY NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `EMAIL_UNIQUE` (`EMAIL` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `taw`.`CIDADE` (
  `IDCIDADE` INT(11) NOT NULL,
  `NOME` VARCHAR(255) NOT NULL,
  `CODCID` DECIMAL(10,0) NULL DEFAULT NULL,
  `ESTADO_idESTADO` INT(11) NOT NULL,
  PRIMARY KEY (`IDCIDADE`),
  INDEX `fk_CIDADE_ESTADO1_idx` (`ESTADO_idESTADO` ASC),
  CONSTRAINT `fk_CIDADE_ESTADO1`
    FOREIGN KEY (`ESTADO_idESTADO`)
    REFERENCES `taw`.`ESTADO` (`idESTADO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `taw`.`DOENÇAS` (
  `idDOENÇAS` INT(11) NOT NULL,
  `NOME` VARCHAR(45) NOT NULL,
  `DESCRICAO` VARCHAR(800) NOT NULL,
  `IMAGEM` VARCHAR(45) NULL DEFAULT NULL,
  `` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDOENÇAS`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `taw`.`ESTADO` (
  `idESTADO` INT(11) NOT NULL,
  `NOMEESTADO` VARCHAR(45) NOT NULL,
  `CODESTADO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idESTADO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `taw`.`ANIMAIS` (
  `IDANIMAIS` INT(11) NOT NULL,
  `NOME` VARCHAR(45) NOT NULL,
  `IDADE` VARCHAR(45) NULL DEFAULT NULL,
  `RACA` VARCHAR(45) NULL DEFAULT NULL,
  `SEXO` VARCHAR(45) NULL DEFAULT NULL,
  `DESCRICAO` VARCHAR(45) NULL DEFAULT NULL,
  `ESPECIE` VARCHAR(45) NULL DEFAULT NULL,
  `USUARIOS_IDUSUARIOS` INT(11) NOT NULL,
  PRIMARY KEY (`IDANIMAIS`),
  INDEX `fk_ANIMAIS_USUARIOS_idx` (`USUARIOS_IDUSUARIOS` ASC),
  CONSTRAINT `fk_ANIMAIS_USUARIOS`
    FOREIGN KEY (`USUARIOS_IDUSUARIOS`)
    REFERENCES `taw`.`USUARIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS `taw`.`IMAGENS` (
  `idIMAGENS` INT(11) NOT NULL,
  `IMAGEM` VARCHAR(45) NOT NULL,
  `USUÁRIO` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idIMAGENS`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
